### ISSUE TITLE
Conflict with Frappe HR PWA

### ISSUE THREAD

**Issue by zuron7** [The-Commit-Company/Raven#723] opened 2024-02-25 13:41 UTC
Note: Both Frappe HR PWA and Raven PWA are installed.

While opening the Raven app, it asks if you would like to open with the Frappe HR PWA.

Browser: Chrome

![Screenshot_20240225-185727](https://github.com/The-Commit-Company/Raven/assets/7473369/98ad99ea-5c88-48e8-b8e2-8cb30de24295)

Browser Fennec F-Droid (Firefox)

![Screenshot_20240225-190732](https://github.com/The-Commit-Company/Raven/assets/7473369/d9fd9bf6-515a-4afb-992a-3f354044c626)

**Comment by nikkothari22** [comment] 2024-02-25 14:38
@zuron7 Cannot reproduce this on iOS. Will check on Android.

Are you able to use both apps though? 

We're thinking of moving to a native app soon, so we might not need to PWA later.

**Closed** 2024-02-26 16:01 UTC
Labels: 🐞 bug, help wanted, 📱 mobile app
