### ISSUE TITLE
I hate the pop up chat box.

### ISSUE THREAD

**Issue by ajiragroup** [The-Commit-Company/raven#1136] opened 2024-10-31 14:44 UTC
This looks not so good. May be bring back the old chat notification on top right beside help and show a pop up notification for incoming messages.

![image](https://github.com/user-attachments/assets/6512418b-0f84-41ac-8d36-c71a4766e3fb)

**Comment by nikkothari22** [comment] 2024-10-31 15:29
> May be bring back the old chat notification on top right beside help and show a pop up notification for incoming messages.

You must be mistaken - we have never had that on Raven.

The In-desk popup interface is optional - you can turn it off in "Raven Settings".

The in-desk interface is also not a priority as of now - you'll notice that it does not support all features that we have on the main Raven interface.

We already have an issue related to the in-desk popup with a list of all improvements needed on it: #647 - but this is not a priority right now since the team is busy working on other tasks.

Also, if you "hate" it, you are free to contribute to the project yourself. I'm gonna close this since it's already a duplicate of #647

**Closed by nikkothari22** 2024-10-31 15:29 UTC
